### ISSUE TITLE
Need to add the other 2 boxes

### ISSUE THREAD

**Issue by fchierad** [VASHtheCHIBI/drag-drop01#1]
Hi My friend,

Next step is to add the other 2 boxes we talked about. Next steps after that (suggestion): 

- Add a right-hand floating bar with the objects that can be copied (not moved) to the 4 main boxes
- Add a trash icon that you can drag the images to. Once the image is dragged to trash the element is simply removed from the page.

Using issues since you have not opened the project part yet ^_^

**Comment by VASHtheCHIBI** [comment]
Finished, except for the copy. Newest functionality is only to move the image. 
Trashcan works to delete. 

Need to figure out how to copy and allow for a deletion. Probably able to be done if I write a different function for Drop and allow drop for the different boxes.

Also want to add the ability to bring back the image if trashcan is used. And to reset to default with the push of a button.

Also need to work on the CSS to center the items.

**Comment by VASHtheCHIBI** [comment]
copy now works. This broke the function of the trash can. 

Trying to set it so that you copy from the main image, but move the secondary images which will cause the Trashcan to work again. There are some issues here that can be read about in the branch called "alternitive_david" as comments in the drag-drop.js file, but that is a topic for a new issue.

Added your pull request to the branch "alternitive_fernando".
